### ISSUE TITLE
Local storage: multitenancy automatic org or repo folder creation

### ISSUE THREAD

**Issue by samifruit514** [kubernetes-helm/chartmuseum#102]
I think folders should be created automatically when we POST a chart if the folder (org/repo) does not exists. At least maybe we should be able to POST new repos/orgs and also DELETE them.

Let me know if you want me to do a PR for this.

**Comment by jdolitsky** [comment]
Hi @samifruit514. Are you using local storage? I believe this works already with cloud storage

**Comment by davidovich** [comment]
In fact, I will be needing this functionality very soon. 

There is a security concern however. How do we protect a repo from abuse ? An attacker could POST a spam of folders, and even theoretically (out of scope for this issue) hide content in the .tgz archive.

@jdolitsky Do you have any hidden insights that might help answer this ?

**Comment by jdolitsky** [comment]
Well, once repos are protected by OAuth (in progress), the request is blocked before any storage operation occurs. But maybe you mean an authorized user could also be an attacker :)

**Comment by davidovich** [comment]
No, I think that is enough (OAuth) for now. I was mistaken in thinking that the hierarchy is created on first POST.  @samifruit514 did you observe differently ?

**Comment by jdolitsky** [comment]
@davidovich the hierarchy IS created on post for cloud storage, but not local, where we will need to do a `mkdir -p`. In which case, this is actually a bug. All storage backends should provide some operational experience.

I think this is also an issue for `GET /index.yaml` on mutlitenancy. In this scenario, I dont think we need to actually do a mkdir until something is uploaded

**Comment by samifruit514** [comment]
Yes I am using localStorage. btw, if you try to POST a folder, you'll get
`{"error":"EOF"}`

do you want me to do a PR? I would change local.go and local_test.go

**Comment by davidovich** [comment]
@samifruit514 Sure go ahead, we will accept this!
