### ISSUE TITLE
Local storage doesn't work when it is removed with its parent directory

### ISSUE THREAD

**Issue by auifzysr** [kubernetes-helm/chartmuseum#115]
### Summary
When the directory specified by `--storage-local-rootdir` is removed with its parent directory, chartmuseum no longer cannot be pushed any charts, but it keeps running.

### How to Reproduce
Suppose chartmuseum is going to run in `/foo/bar`.

1. Chdir to `/foo/bar`.
```bash
$ cd /foo/bar
```

2. Boot up chartmuseum with `--storage="local" --storage-local-rootdir="./baz"`.
```bash
$ /usr/local/bin/chartmuseum --storage="local" --storage-local-rootdir="./baz"
```

3. Push a chart to the chartmuseum.

```bash
$ helm repo add chartmuseum http://chartmuseumhost:8080
$ helm push somechartA-1.0.0.tgz chartmuseum
```

4. Remove `/foo/bar`.
```bash
$ rm -rf /foo/bar
```

5. Try to push a chart to the chartmuseum.
```bash
$ helm push somechartB-1.0.0.tgz chartmuseum
Pushing somechartB-1.0.0.tgz to chartmuseum...
Error: 500: mkdir baz: no such file or directory
Error: plugin "push" exited with error
$
```

On the other hand, removing `/foo/bar/baz` doesn't make any troubles.

Is this a specification, or a bug?

### Suggestion
In my opinion, one of the followings would be a solution. As for 1., I have already [implemented it](https://github.com/auifzysr/chartmuseum/commit/ac531f19bc7d34b5f341195214404718a89c47d4).
1. Let chartmuseum recreate the directory including its parent.
2. Fix the error message to provide more information.

**Comment by jdolitsky** [comment]
@auifzysr hi. thanks for opening, took a look at your change

I think that a chdir etc. is unnecessary. I think the solution is just to make a minor change to `NewLocalFilesystemBackend` to convert incoming rootDirectory to absolute path before constructing the LocalFilesystemBackend

**Comment by auifzysr** [comment]
@jdolitsky Hi. I [fixed it](https://github.com/auifzysr/chartmuseum/commit/1e0d97ca59a3fc3264dee7584fc2075042c11391) by using `filepath.Abs`. I'm afraid I couldn't find a way to use `filepath.Abs` without importing `path/filepath` instead of just using `pathutil "path"`, so it is newly imported.

I also thought that just replacing `pathutil "path"` with `pathutil "path/filepath"` would be alternative, but I didn't do that. `pathutil "path"` and `pathutil "path/filepath"` seem to have the similar spec's methods, but I don't know the internal differences.

**Comment by jdolitsky** [comment]
@auifzysr hey! i would just lave it as `"path/filepath"`, but otherwise the change looks good! Feel free to open a PR!

**Comment by jdolitsky** [comment]
thank you!
