### ISSUE TITLE
helm push uses "chart" as form field which could differ from chartmuseum configuration

### ISSUE THREAD

**Issue by davidovich** [kubernetes-helm/chartmuseum#124]
We use the `CHART_POST_FORM_FIELD_NAME=chartfile` configuration option (to support legacy script clients using curl to upload charts). 

Right now, the helm push plugin hardcodes the form field to "chart" which does not allow it's usage with our CHART_POST_FORM_FIELD_NAME configured instance. Using `chart` is practical, as we do not want to expose this internal configuration to the helm plugin (or users), but having the knob to change the form field is also wanted. We can have both.

I propose that chartmuseum support the `chart` form field as a baked-in default (as a cli supported upload interface definition), and support additionally the CHART_POST_FORM_FIELD_NAME. In other words these two scenarios would be allowed:

* helm push will be able to use the default `chart` as supported by default.
* clients will be allowed to upload with `chartfile` as form field as configured by `CHART_POST_FORM_FIELD_NAME`.

**Comment by jdolitsky** [comment]
Yes, this sounds good to me!
