### ISSUE TITLE
Health route no longer at /health when using depth=1

### ISSUE THREAD

**Issue by fabzo** [kubernetes-helm/chartmuseum#140]
When starting chartmuseum 0.7.0 with the env variable DEPTH set to 1 the /health route is no longer found at the context root, but at /some-string/health.

As a quick fix for my deployment I adjusted the kubernetes liveness and readiness probes to go to /depth1/health instead of /health in my local copy of the [chartmuseum chart](https://github.com/kubernetes/charts/tree/master/stable/chartmuseum).

I assume the health route should remain at the context root regardless of the configured depth.

**Comment by jdolitsky** [comment]
@fabzo good find, yes it definitely should

**Comment by jdolitsky** [comment]
@fabzo this hsould be fixed on master. Can you please try with the "latest" docker image tag and let us know if this is working for you? Thanks!

**Comment by fabzo** [comment]
Thanks for the fast response. I will test it tomorrow and report back.

**Comment by fabzo** [comment]
Took me a while to get back to it. I reverted the liveness and readiness probes to the /health route and deployed it with the latest image. 

Looks good to me:
`{
  "M": "[75] Request served",
  "path": "/health",
  "method": "GET",
  "statusCode": 200,
...
}`

Thanks for the fix :-)

**Comment by jdolitsky** [comment]
@fabzo great thanks for verifying!
