### ISSUE TITLE
How to download charts from chartmuseum?

### ISSUE THREAD

**Issue by plokimju** [kubernetes-helm/chartmuseum#141]
Hi ,

I am trying to download charts from chart museum. But as per the documentation. There is only a way to list the charts but not to download them to local. Please let me know possible way to achieve this?

**Comment by jdolitsky** [comment]
@plokimju can you elaborate?

ChartMuseum meant to be directly with the Helm client, so you can do something like
```
helm repo add chartmuseum http://localhost:8080
helm fetch chartmuseum/mychart
```

This will download latest chart .tgz to current directory

**Comment by plokimju** [comment]
Hi @jdolitsky ,

Thanks for your prompt response:

When I do a "helm fetch" I see:

  helm fetch chartmuseum/workflowengineservice
Error: chart "abc" matching  not found in chartmuseum index. (try 'helm repo update'). No chart version found for **abc-**

**Comment by plokimju** [comment]
@jdolitsky  - I am able to see the chart index.yaml. Interestingly error append "- " at the end of chartmuseum   "No chart version found for **abc-**"

**Comment by jdolitsky** [comment]
@plokimju would you mind sharing contents on index.yaml? Have you added the repo with `helm repo add` ?

**Comment by plokimju** [comment]
@jdolitsky  - yes I did

$ helm repo list
NAME            URL
chartmuseum     http://<endpoint>:8080/<repo>/


$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "chartmuseum" chart repository
Update Complete. ⎈ Happy Helming!⎈

Index.yaml

$ curl http://<endpoint>:8080/<repo>/index.xml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0apiVersion: v1
entries:
  abc:
  - apiVersion: v1
    appVersion: 0.1.1-SNAPSHOT
    created: "2018-06-14T19:00:10.459Z"
    description: A Helm chart for Kubernetes
    digest: 47a71903ea865dff80a2837496ad7a90d949ef2b9dc84e5c2090b0d771
    name: abc
    urls:
    - charts/abc-0.1.1-SNAPSHOT.tgz
    version: 0.1.1-SNAPSHOT
generated: "2018-06-20T19:12:47Z"

**Comment by plokimju** [comment]
closing as I am able get the the charts with curl

**Comment by stevie-** [comment]
Also hit this issue.

Found out that the problem is related to the `version`. If version has a suffix with a dash `-`, `helm install chartmuseum/CHART` can't find the chart version. 
Sematic Versioning supports dashes and Suffixes. Not sure if bug in helm or chartmuseum.

**Comment by leprechaun** [comment]
Well, it's not a bug, but an annoyance for people like us, I guess.

SemVer, and thus helm, consider that version strings w/ an additional `-tag` are actually pre-releases. Helm is simply not showing you, or using those by default.

I see 3 easy-ish solutions here:

- Specify `--devel` in your `helm` calls, so that it considers those pre-releases
- Specify `--version $VERSION` in your helm calls
- Move the git sha from version, and specify your complete version string in the charts' `appVersion` field

Annoying.

This didn't affect me until I upgraded to helm 2.10
