### ISSUE TITLE
GCS auth

### ISSUE THREAD

**Issue by volatilemolotov12** [kubernetes-helm/chartmuseum#144]
There is no documentation on how to provide google storage credentials to chartmuseum. 

i get :

panic: dialing: google: could not find default credentials.

when trying to run in docker using e STORAGE="google" --storage-google-bucket="test-helm-repo"

**Comment by jdolitsky** [comment]
@volatilemolotov12 thanks for opening, I've added a short note to the README, let us know if youre able to get things running

**Comment by volatilemolotov12** [comment]
Great, that works. Maybe you should also add that if using docker one should mount the key inside because i lost like half an hour trying haha. 

Once again thanks for quick reply.
