### ISSUE TITLE
Add restricted IAM Policy for S3 Storage in documentation

### ISSUE THREAD

**Issue by qrevel** [kubernetes-helm/chartmuseum#31]
We already talked about this in #2.
The goal is to get a restricted IAM Policy for S3 Storage.

**Comment by jdolitsky** [comment]
@qrevel quick question about this (several weeks later) - does the following statement
```
    {
        "Sid": "AllowListObjects",
        "Effect": "Allow",
        "Action": [
            "s3:ListBucket"
        ],
        "Resource": "*"
    }
```
need to apply to "*"? Have you tried just "arn:aws:s3:::my-s3-bucket" ?

**Comment by qrevel** [comment]
I remember having a 403 when using a resource on `s3:ListBucket` so I tested everything again and here was my mistake. I used `arn:aws:s3:::my-s3-bucket/*` instead of `arn:aws:s3:::my-s3-bucket` so the ListBucket operation didn't apply on the bucket itself.

I created a PR to fix it.

**Comment by jdolitsky** [comment]
@qrevel thank you for checking that!
