### ISSUE TITLE
Chart already exists should not be a 500

### ISSUE THREAD

**Issue by iMartyn** [kubernetes-helm/chartmuseum#42]
500 indicates something went wrong at the server side.

I suggest chartmuseum should return a 403 Forbidden (as it's not overwriting) or vaguely possibly 400 Bad Request (as you should not try to overwrite a chart).

**Comment by jdolitsky** [comment]
Yes, thanks. Good call. There are several errors that have defaulted to use 500

**Comment by davidovich** [comment]
The responses are correct when using `mutlipart/form-data`. As this was described as wanted to be deprecated, we never changed the error code handling on the binary data code path.

`multipart/form-data` code handles correctly duplicates and reports them as 409 conflict:
https://github.com/kubernetes-helm/chartmuseum/blob/89c1a7672dd0ab044f65c06873c029b647fb5935/pkg/chartmuseum/handlers.go#L149

But not in the classical binary path:
https://github.com/kubernetes-helm/chartmuseum/blob/89c1a7672dd0ab044f65c06873c029b647fb5935/pkg/chartmuseum/handlers.go#L211-L242

We may want to deprecate the binary submission, as [was once suggested](https://github.com/kubernetes-helm/chartmuseum/issues/7#issuecomment-335517636) by @jdolitsky or update the code handling appropriately.
