### ISSUE TITLE
Question: vSphere Cloud Provider storage

### ISSUE THREAD

**Issue by dkirrane** [kubernetes-helm/chartmuseum#52]
Hi,

The documentation mentions Google Cloud Storage, Amazon S3, and Microsoft Azure Blob Storage.

Am I correct in assuming VCP storage would work as well?

**Comment by jdolitsky** [comment]
@dkirrane I'm not too familiar with it. Is VCP block level storage or file level storage? Assuming it is file level, you can use the ChartMuseum `--storage="local"` option.

**Comment by dkirrane** [comment]
Thanks I'll try local.
What would the command be for the Docker image?
```
docker run --rm -it \
  -p 8080:8080 \
  -e PORT=8080 \
  -e DEBUG=1 \
  -e STORAGE="local" \
  -e STORAGE_LOCAL_ROOTDIR="C:/HelmCharts" \
  -v C:/HelmCharts:/root/???? \
  chartmuseum/chartmuseum:latest
```

**Comment by jdolitsky** [comment]
@dkirrane, yes very close, the container dir for the volume must match
STORAGE_LOCAL_ROOTDIR, and should be a Linux path.

So something like

docker run --rm -it \
  -p 8080:8080 \
  -e PORT=8080 \
  -e DEBUG=1 \
  -e STORAGE="local" \
  -e STORAGE_LOCAL_ROOTDIR="/charts" \
  -v C:/HelmCharts:/charts \
  chartmuseum/chartmuseum:latest
