### ISSUE TITLE
How to add chartmuseum as an App Repository in Kubeapps

### ISSUE THREAD

**Issue by nagarjunac** [kubernetes-helm/chartmuseum#62]
Hi,
I am very amazed with the chartmuseum. May I know if there is a way to add chartmuseum as an App Repository in Kubeapps. This can help me manage and deploy my helm releases  in a very nice way.

**Comment by jdolitsky** [comment]
@nagarjunac thanks!

I assume you are talking about running your own Monocular instance? If so you can check out the configuration instructions here: https://github.com/kubernetes-helm/monocular/blob/master/deployment/monocular/README.md#configuring-chart-repositories

cc @prydonius

**Comment by prydonius** [comment]
thanks @jdolitsky. @nagarjunac if you're talking about the new Kubeapps dashboard, you should be able to add your ChartMuseum repo as any other Helm Chart repository in the configuration page (see https://github.com/kubeapps/kubeapps/blob/master/docs/dashboard.md#add-more-chart-repositories). It's the same name/URL you'd enter with `helm repo add`.

**Comment by nagarjunac** [comment]
@prydonius I think I have tried it the same way, but my charts were not visible under charts page. I will try one more time and let you know if it works.

**Comment by nagarjunac** [comment]
thanks @jdolitsky .

**Comment by jdolitsky** [comment]
closing since question for the KubeApps team

**Comment by prydonius** [comment]
@nagarjunac did this work for you in the end?

**Comment by hayderimran7** [comment]
adding the chartmuseum repository from UI fails for me :/ [monocular-fail](https://i.imgur.com/2NjVzCQ.png)

**Comment by jdolitsky** [comment]
@hayderimran7 what do you get with

```
curl -v http://chartmuseum.local.com/index.yaml
```
?

**Comment by hayderimran7** [comment]
@jdolitsky 
```
curl -v http://<REDACTED>.com/index.yaml
*   Trying 172.33.60.239...
* TCP_NODELAY set
* Connected to <REDACTED>.com (172.33.60.239) port 80 (#0)
> GET /index.yaml HTTP/1.1
> Host: <REDACTED>.com
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/x-yaml
< X-Request-Id: 1821cab0-1a72-4beb-a945-c2bc285975d1
< Date: Mon, 09 Apr 2018 22:01:36 GMT
< Content-Length: 1353
<
apiVersion: v1
entries:
  mysql:
  - apiVersion: v1
    created: 2018-04-05T19:43:32Z
    description: A Helm chart for Kubernetes
    digest: e85152ac6ae89f53341507ac8669db98dc083f797dc5fed8039f6f8bdc9f8dcd
    name: mysql
    urls:
    - charts/mysql-0.1.0.tgz
    version: 0.1.0
  stem-mysql-local:
  - apiVersion: v1
    created: 2018-04-09T19:23:54Z
    description: A test specfic MySQL Helm chart using in dev (local) and regression
      environments
    digest: 4010b3dca5db1e12928d0259a8ebcd749c91cf064f8b135d1509de8fe4c1b3a4
    name: stem-mysql-local
    urls:
    - charts/stem-mysql-local-1.0.0+2-bfad995.tgz
```

**Comment by jdolitsky** [comment]
@hayderimran7 that repo looks healthy, I would open/check for an issue in the monocular queue: https://github.com/kubernetes-helm/monocular/issues

Maybe javascript debug console will tell you more

**Comment by hayderimran7** [comment]
@jdolitsky thanks for the help - yep looks like an angularJS error to me [monocular-error](https://i.imgur.com/GiefJ7H.png)

**Comment by prydonius** [comment]
@hayderimran7 can you open an issue in the Monocular repo @jdolitsky linked to. It would also be helpful if you could screenshot the Network tab of the chrome inspection pane to see the response from the failing request. Cheers!
