### ISSUE TITLE
Root url not using authentication when API is

### ISSUE THREAD

**Issue by christopherhein** [kubernetes-helm/chartmuseum#66]
It seems like the root `/` isn't using authentication when the `/api` requires it. Is this expected?

I see there is work going on in #59 and #64 and I'm guessing this is vestigial from #29 when the root was the healthcheck.

Is there a reason we leave the `/` unauthenticated?

**Comment by jdolitsky** [comment]
@christopherhein no reason really. I suppose that should have the same access control as /index.yaml

**Comment by christopherhein** [comment]
Okay, thank you! @jdolitsky

**Comment by jdolitsky** [comment]
@christopherhein this fix is now in latest binary and docker image

**Comment by christopherhein** [comment]
Wow, thank you for the fast action @jdolitsky !

**Comment by christopherhein** [comment]
In case you didn't see, I'm adding a module to the [AWS Workshop for Kubernetes](https://github.com/aws-samples/aws-workshop-for-kubernetes) that walks someone through deploying `chartmuseum` using `helm` and sets up basic auth w/ an ELB to front it. If you have some time I'd love to get your review as well - https://github.com/aws-samples/aws-workshop-for-kubernetes/pull/395

Thanks again!

**Comment by jdolitsky** [comment]
@christopherhein thats awesome! I'll take a look

I've cut a 0.4.2 that contains this fix, and also this update to the Helm chart is ready to be merged:
https://github.com/kubernetes/charts/pull/4091
