### ISSUE TITLE
Multitenant server should use cache

### ISSUE THREAD

**Issue by jdolitsky** [kubernetes-helm/chartmuseum#73]
Multitenant server is currently generating index.yaml upon every request, should be switched to use the cache

**Comment by davidovich** [comment]
Currently, the state of the storage is the one true reference for the state of repository. I just wanted to add that adding a cache managed through the museum will break this and transfer the 'truth' responsability to the cache layer. 

I can see a problem where the cache is not reconciled between multiple pod instances, and I am not sure how to resolve this concern.

This also means that operations on the storage cannot be made without funneling all the changes throughf chartmuseum. This may be a control that is not wanted given the caching benefits, I just wanted to state the departure on the previous design.

**Comment by jdolitsky** [comment]
This issue may be misleading. The only aim with this is to get mutlitenant server up-to-par with how singletenant server is doing things.

> adding a cache managed through the museum will break this and transfer the 'truth' responsability to the cache layer

I'm planning to still treat storage as source of truth. The cache is simply a copy of the most recent `ListObjects` result, so that is can be compared to the result of `ListObjects` for an incoming request, to prevent loading every single .tgz on every time. This is how it works with singletenant today.

> I can see a problem where the cache is not reconciled between multiple pod instances, and I am not sure how to resolve this concern.

Again, the `ListObjects` is called every request. So even if two pods are not up-to-date in terms of the cache, they will eventually become so, despite extra API calls. The result of index.yaml will always be current based on storage. Optional Redis will come into play here as well.
