### ISSUE TITLE
make repo subdirectroy of multitenancy optional

### ISSUE THREAD

**Issue by davidovich** [kubernetes-helm/chartmuseum#76]
Right now, the current multitenancy design mandates a structure in this style: `org1/repoa`, `org2/repoa`. While I still think two levels are a good idea in a centralized hosting scenario, I also think that it might be overkill for a corporate scenario where only one chartmuseum is present and one level (the org level) would be used for different teams. It appears that the file structure of the repos could be relaxed when the org separation is enough for simple use cases.

The two levels could be useful for these corporate teams, for providing something like dev / staging / prod, but can also be too fine-grained for a team only wanting a separate namespace.

This issue is opened to discuss the merits of an optional two level separation.

**Comment by jdolitsky** [comment]
@davidovich that sounds reasonable.

Just to clarify, you are looking for multitenany routes such as
- `/repo1/index.yaml`
- `/repo2/index.yaml`
- `/repo3/index.yaml`

?

**Comment by jdolitsky** [comment]
@davidovich what if... instead of a `--multitenancy` flag, we add something such as `--depth=<int>`? And the routing would change based on that param?

`--depth=0` (default) would give you singletenant as it works today:
```
/index.yaml
```

`--depth=1` would give you what you're looking for:
```
/<repo>/index.yaml
```

`--depth=2` would give you what multitenant is today:
```
/<org>/<repo>/index.yaml
```

And people could even decide to do something with `--depth=3` or more:
```
/<org>/<team>/<repo>/index.yaml
```

Thoughts?

**Comment by davidovich** [comment]
Yes I think this would provide the wanted value. Could I suggest adding `--tenant-depth` instead of changing `--multitenancy` ?

**Comment by jdolitsky** [comment]
Once we're ready to "release" multitenancy, I'd like to just have the `--depth` or `--tenant-depth` flag, which defaults to 0. If things are done correctly the user should see no change, and there will be no multitenancy unless explicitly specified with the flag.

For now, until everything is well tested, the new flag would take no effect unless `--multitenancy` is also used.

I very much intend to break this API without warning, hence the bold "**experimental**" in the readme :)
