### ISSUE TITLE
Enable CRUD API (Chart Manipulation routes) in multitenant server

### ISSUE THREAD

**Issue by jdolitsky** [kubernetes-helm/chartmuseum#78]
We could likely get away with using the same routes:
- `POST /api/charts` - upload a new chart version
- `POST /api/prov` - upload a new provenance file
- `DELETE /api/charts/<name>/<version>` - delete a chart version
- `GET /api/charts` - list all charts
- `GET /api/charts/<name>` - list all versions of a chart
- `GET /api/charts/<name>/<version>` - describe a chart version

We just need a way to pass in the name of the repo. Should we do so in the headers?
```
ChartMuseum-Repo: org1/repo1
```
or eliminate the `--data-binary` option and make it a form field (@davidovich)?
```
curl -F "repo=org1/repo1" -F "chart=@mychart-0.1.0.tgz" http://localhost:8080/api/charts
```

?
cc @alexei-led @itaysk

**Comment by davidovich** [comment]
I have some ideas, but will have to come back on this monday.

**Comment by jdolitsky** [comment]
@jzelinskie also curious about your take on uploads given experience w app registry etc

**Comment by jdolitsky** [comment]
After talking with a few people, here are the proposed routes:
- `POST /api/<repo>/charts` - upload a new chart version
- `POST /api/<repo>/prov` - upload a new provenance file
- `DELETE /api/<repo>/charts/<name>/<version>` - delete a chart version (and corresponding provenance file)
- `GET /api/<repo>/charts` - list all charts
- `GET /api/<repo>/charts/<name>` - list all versions of a chart
- `GET /api/<repo>/charts/<name>/<version>` - describe a chart version

In the case of single tenant (`--depth=0`) setup, `<repo>` is simply an empty string "", so the routes are identical to how they are currently. This will allow us to remove the old branch of code sooner (see #82).

For `--depth=0` the upload would look like `POST /api/charts`

For `--depth=1` the upload would look like `POST /api/myrepo/charts`

For `--depth=2` the upload would look like `POST /api/myorg/myrepo/charts`

**Comment by davidovich** [comment]
> POST /api/<repo>/prov - upload a new provenance file

This may be a good time to remove that and rely only the form data.

**Comment by jdolitsky** [comment]
Although I agree that we should deprecate it, I think now is not the time. I'd like to make a release with multitenancy support such as 0.5.0, without breaking backwards compatibility. Should be removed for 1.0.0 though.

**Comment by jzelinskie** [comment]
@jdolitsky Uploading for Helm Charts can be very much so simplified down to one single multipart upload via HTTP POST, since they are never particular large.

The complexity for App Registry is around supporting various formats which could potentially bundle container images with manifests like a Helm chart.

OT: I do think that the prov files are better stored in some centralized metadata storage like Grafeas, rather being served the from the same place you're receiving the chart.

**Comment by jdolitsky** [comment]
@jzelinskie awesome, ty for the input
