### ISSUE TITLE
Rename port "chartmuseum" to "http" for Istio compatibility

### ISSUE THREAD

**Issue by KrustyHack** [kubernetes-helm/chartmuseum#80]
Ay,

Is it possible to rename port "chartmuseum" to "http" (or even "http-chartmuseum") in chartmuseum service to allow compatibility with istio ingress ?

Regards,

**Comment by jdolitsky** [comment]
Hi, are you running the chartmuseum Helm chart? If I understand correctly, I think we just need to update this line: https://github.com/kubernetes/charts/blob/master/incubator/chartmuseum/templates/service.yaml#L23

**Comment by KrustyHack** [comment]
Ay,

Yes, that's right :).

Regards,

**Comment by jdolitsky** [comment]
@KrustyHack this is now fixed in incubator/chartmuseum 0.4.5. Thanks!
