### ISSUE TITLE
Use dep as package manager

### ISSUE THREAD

**Issue by davidovich** [kubernetes-helm/chartmuseum#81]
The go community is moving to [dep ](https://github.com/golang/dep) as the official packaging solution.

glide is in [maintenance mode only](https://github.com/Masterminds/glide#golang-dep).

**Comment by SlickNik** [comment]
@jdolitsky @davidovich Any objections to me taking a look into this one?

**Comment by davidovich** [comment]
Sure! Thank you for offering!
Le mer. 21 mars 2018 à 03:04, Nikhil Manchanda <notifications@github.com> a
écrit :

**Comment by jdolitsky** [comment]
go for it @SlickNik !
