### ISSUE TITLE
Feature request: Add a mechanism to specify configuration

### ISSUE THREAD

**Issue by davidovich** [kubernetes-helm/chartmuseum#94]
The current implementation uses command line switches to control the configuration of the chartmuseum. This will become very hard to maintain and or implement if we want to support per tenant configurations.

We could add a configuration file to allow varying options for the chartmuseum startup.

**Comment by jdolitsky** [comment]
Yes, we need this. I think that you should be able to use a simple .conf file, or a sql database for advanced use cases.

cc @itaysk
